### ISSUE TITLE
KeyError: 'PROJ_LIB'

### ISSUE THREAD

**Issue by kev1807** [conda-forge/basemap-feedstock#42] opened 2018-12-30 14:57 UTC
Hi everybody, 

I am probably not making any friends by opening another issue on this Error, however none of the researched solutions fixed it for me ... 
I experience this issue, when I attempt to rebuild the basic tutorial for basemap usage:
I am working with PyCharm Community Edition, using Win 10. 
```
`from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

map = Basemap()
map.drawcoastlines()

plt.show()`
```

> Traceback (most recent call last):
>   File "C:/Users/KW/PycharmProjects/Abweichung/map2.py", line 1, in <module>
>     from mpl_toolkits.basemap import Basemap
>   File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 155, in <module>
>     pyproj_datadir = os.environ['PROJ_LIB']
>   File "C:\ProgramData\Anaconda3\lib\os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'PROJ_LIB'

conda list
https://pastebin.com/c12hZvpC

conda info
https://pastebin.com/0inc2PzE

Following some threads I read, I reinstalled anaconda3 today and looked for my PATH-Variable. 
I haven't set up any environments as I only started working with Python again in a Course on data analysis a few weeks back. I've read a few threads back (there are plenty closed on the issue) that it works with an environment set up for conda - why so? 

And can I simply change the interpreter specified in PyCharm to the environment or would you restart my project (which I started today, so not much trouble reinstalling conda again .... (However, I'd love to avoid it, since I have a presentation on my topic in 8 days ) )

**Comment by ocefpaf** [comment] 2019-01-03 21:16
>  that it works with an environment set up for conda - why so?

With modern conda everything works. I can say anything about pycharm though.

Closing this b/c I cannot reproduce it.

**Closed by ocefpaf** 2019-01-03 21:16 UTC
